services:

  postgres:
    image: postgres:16

    container_name: ollive-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ollive

    ports:
      - "5432:5432"

  redis:
    image: redis:7

    container_name: ollive-redis

    ports:
      - "6379:6379"

  backend:
    build:
      context: ./apps/backend

    container_name: ollive-backend

    ports:
      - "3000:3000"

    depends_on:
      - postgres
      - redis

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ollive
      REDIS_HOST: redis
      REDIS_PORT: 6379
      INGESTION_URL: http://backend:3000/ingest
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  worker:
    build:
      context: ./apps/worker

    container_name: ollive-worker

    depends_on:
      - postgres
      - redis

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ollive
      REDIS_HOST: redis
      REDIS_PORT: 6379

  frontend:
    build:
      context: ./apps/frontend

    container_name: ollive-frontend

    ports:
      - "3001:3001"

    depends_on:
      - backend